<!-- Remover do domingo -->
<div class="modal" tabindex="-1" role="dialog" id="remo_domingo">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_domingo.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/tarefasDomingo.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover da segunda -->
<div class="modal" tabindex="-1" role="dialog" id="remo_segunda">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_segunda.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/tarefasSegunda.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover da terca -->
<div class="modal" tabindex="-1" role="dialog" id="remo_terca">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_terca.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/tarefasTerca.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover da quarta -->
<div class="modal" tabindex="-1" role="dialog" id="remo_quarta">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_quarta.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/tarefasQuarta.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover do quinta -->
<div class="modal" tabindex="-1" role="dialog" id="remo_quinta">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_quinta.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/tarefasQuinta.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover da sexta -->
<div class="modal" tabindex="-1" role="dialog" id="remo_sexta">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_sexta.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/tarefasSexta.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover do sabado -->
<div class="modal" tabindex="-1" role="dialog" id="remo_sabado">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_sabado.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/tarefasSabado.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover do metas -->
<div class="modal" tabindex="-1" role="dialog" id="remo_metas">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_metas.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/metas.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

<!-- Remover do importante -->
<div class="modal" tabindex="-1" role="dialog" id="remo_importante">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <center>
                <h5 class="modal-title">Remoção de tarefas</h5>
              </center>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form action="php/remover/remo_importante.php" method="POST">
              <div class="modal-body">
                  <div class="row">
                      <div class="form-group col-sm-12 col-12">
                        <div class="form-check">
                          <?php include "php/importante.php";?>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
              <button class="btn btn-danger texto" type="submit">Remover</button>
              </div>
          </form>
      </div>
  </div>
</div>

